//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MtrDev.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MtrDev.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event BackgroundImageLayoutChanged not supported.
        /// </summary>
        internal static string BackgroundImageLayoutChanged {
            get {
                return ResourceManager.GetString("BackgroundImageLayoutChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event {0} is not supported.
        /// </summary>
        internal static string EventNotSupported {
            get {
                return ResourceManager.GetString("EventNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop not supported.
        /// </summary>
        internal static string WebView2AllowDropNotSupport {
            get {
                return ResourceManager.GetString("WebView2AllowDropNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image layout not supported.
        /// </summary>
        internal static string WebView2BackgroundImageLayoutNotSupported {
            get {
                return ResourceManager.GetString("WebView2BackgroundImageLayoutNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image not supported.
        /// </summary>
        internal static string WebView2BackgroundImageNotSupported {
            get {
                return ResourceManager.GetString("WebView2BackgroundImageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor not supported.
        /// </summary>
        internal static string WebView2CursorNotSupported {
            get {
                return ResourceManager.GetString("WebView2CursorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled not supported.
        /// </summary>
        internal static string WebView2EnabledNotSupported {
            get {
                return ResourceManager.GetString("WebView2EnabledNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightToLeft not supported.
        /// </summary>
        internal static string WebView2RightToLeftNotSupported {
            get {
                return ResourceManager.GetString("WebView2RightToLeftNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text not supported.
        /// </summary>
        internal static string WebView2TextNotSupported {
            get {
                return ResourceManager.GetString("WebView2TextNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitCursor not supported.
        /// </summary>
        internal static string WebView2UseWaitCursorNotSupported {
            get {
                return ResourceManager.GetString("WebView2UseWaitCursorNotSupported", resourceCulture);
            }
        }
    }
}
